name: Terra-CI

on:
  push:

jobs:
  terrafrom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.6
      - name: Printing terraform version
        run: terraform --version