name: Terra-CI
on:
  push:
    # paths:
    #   - "01-VPC"
jobs:
  terrafrom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.6
      - name: Printing terraform version
        run: git log --oneline && terraform --version 
      - name: Get the changed directory 
        run: bash -v get_dir.sh