name: Terra-CI

on:
  push:
    # paths:
    #   - "01-VPC"

jobs:
  terrafrom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.6
      - name: Printing terraform version
        run: git log --oneline && terraform --version && git diff --name-only HEAD@{0} HEAD@{1} | awk -F / '{print $1}'
      # - name: Changed directory 
      #   id: ch_dir 
      #   run: |
      #     echo "::set-output name=CH_DIR::$(git diff --name-only HEAD@{0} HEAD@{1} | awk -F / '{print $1}')"
      # - name: Printing Changed directory name
      #   run: echo "{{ steps.ch_dir.outputs.CH_DIR }}"